spring:
  application:
    name: etarms
  datasource:
    url: jdbc:postgresql://ep-fragrant-band-a1rstzk7-pooler.ap-southeast-1.aws.neon.tech:5432/etarms?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_hq6PgdQ0KDaB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    baseline-on-migrate: false
    baseline-version: 1

jwt:
  secret: "etarms-secret-key-should-be-at-least-256-bits-long"
  expiration-ms: 3600000
  issuer: "etarms-backend"
cloudinary:
  cloud-name: drsbk3hfn
  api-key: 958439486689679
  api-secret: bAkP0MZcB7VC91MmYe8QzSD0A18
#cloudinary:
#  cloud-name: ${CLOUDINARY_CLOUD_NAME:drsbk3hfn}
#  api-key: ${CLOUDINARY_API_KEY:}
#  api-secret: ${CLOUDINARY_API_SECRET:}
